const CapableData = [
  {
    id: 1,
    mainclass: "capable-main grid grid-two-columns",
    boxclass: "capable-box",
    imgclass: "capable-img",
    top_heading: "CAPABILITIES",
    main_heading: "Actionable business and strategic insights",
    desc: `We empower businesses with actionable, data-driven insights that enhance strategic decision-making.`,
    desc2: `By transforming raw data into valuable intelligence, we enable organizations to implement meaningful improvements.`,
    desc3: `Companies utilizing QaaS have reported up to 25% faster decision-making, allowing them to respond more effectively to market dynamics and customer demands.`,
    img: "/Images/img5.jpg",
  },
  {
    id: 2,
    mainclass: "capable-main grid grid-two-columns",
    boxclass: "capable-box data-col",
    imgclass: "capable-img img-col",
    main_heading: "Early detection of potential customer issues",
    desc: `Rapidly identifying customer issues is essential for effective service. Our clients have experienced up to a 25% decrease in the time taken to resolve customer problems`,
    desc2: `We accelerate the detection cycle, enabling quicker responses to customer concerns.`,
    img: "/Images/img2.jpeg",
  },
  {
    id: 3,
    mainclass: "capable-main grid grid-two-columns",
    boxclass: "capable-box",
    imgclass: "capable-img",
    main_heading: "Functions as an independent monitoring entity",
    desc: `QaaS provides a unified approach to manage multiple vendors, driving process standardization and consistency.`,
    desc2: `Businesses that adopt QaaS have achieved up to a 40% reduction in process variation across different vendors`,
    img: "/Images/img7.jpg",
  },
  {
    id: 4,
    mainclass: "capable-main grid grid-two-columns",
    boxclass: "capable-box data-col",
    imgclass: "capable-img img-col",
    main_heading: "Drives continuous improvement",
    desc: `Traditional quality audits often fail to drive continuous improvement effectively.`,
    desc2: `QaaS transforms this approach by fostering dynamic processes that evolve with your business.`,
    desc3: `Companies using QaaS have seen a remarkable 30% increase in continuous improvement initiative.`,
    img: "/Images/img8.jpg",
  },
  {
    id: 5,
    mainclass: "capable-main grid grid-two-columns capable-last",
    boxclass: "capable-box",
    imgclass: "capable-img",
    main_heading: "Accelerate AGI Deployment",
    desc: `At Qualiinsight, we aim to accelerate the advancement and deployment of Artificial General Intelligence (AGI) through our innovative framework of QaaS.`,
    desc2: `By integrating expert human feedback, we enhance AGI outputs, ensuring they meet the highest quality standards.`,
    desc3: `Our commitment to ethical practices and continuous improvement fosters responsible AGI deployment, promoting fairness and inclusivity.`,
    img: "/Images/img9.jpeg",
  },
];

export default CapableData;
